# Generated by Django 4.1.5 on 2023-01-09 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(verbose_name='created at')),
                ('last_changed_at', models.DateTimeField(verbose_name='last changed at')),
                ('power_type', models.CharField(max_length=50)),
            ],
        ),
    ]
