# Generated by Django 4.1.5 on 2023-01-10 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemons', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='author',
            field=models.CharField(default='ben', max_length=100),
        ),
    ]
