# Generated by Django 4.1.5 on 2023-01-12 08:19

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('pokemons', '0002_pokemon_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateTimeField(verbose_name='born at')),
                ('where_born', models.CharField(max_length=100, verbose_name='what location concieved at')),
                ('is_dead', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='pokemon',
            name='author',
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='power_type',
            field=models.CharField(choices=[('fi', 'Fire'), ('wa', 'Water'), ('ai', 'Air'), ('ea', 'Earth'), ('el', 'Electric'), ('ps', 'Psychic'), ('da', 'Dark'), ('li', 'Light')], max_length=2),
        ),
        migrations.CreateModel(
            name='PokemonInstance',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('4c7661b3-4f0c-472b-9529-9ba7de6463c3'), primary_key=True, serialize=False)),
                ('nickname', models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='custom name given by owner')),
                ('evolution', models.CharField(choices=[('e0', 'Evolution 0'), ('e1', 'Evolution 1'), ('e2', 'Evolution 2'), ('e3', 'Evolution 3'), ('e4', 'Evolution 4'), ('e5', 'Evolution 5'), ('e6', 'Evolution 6')], default='e0', max_length=2)),
                ('current_owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pokemons.person')),
                ('owner_history', models.ManyToManyField(related_name='current_owner', to='pokemons.person')),
                ('pokemon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pokemons.pokemon')),
            ],
        ),
        migrations.AddField(
            model_name='pokemon',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pokemons.person'),
        ),
    ]
