# Generated by Django 4.1.5 on 2023-01-12 15:15

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('pokemons', '0003_person_remove_pokemon_author_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemoninstance',
            name='id',
            field=models.UUIDField(default=uuid.UUID('3bb878e4-63fc-4846-a69e-6330431601f1'), primary_key=True, serialize=False),
        ),
    ]
