# Generated by Django 4.1.5 on 2023-01-12 15:24

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('pokemons', '0004_alter_pokemoninstance_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='first_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='person',
            name='last_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='person',
            name='where_born',
            field=models.CharField(max_length=80, verbose_name='what location concieved at'),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='pokemoninstance',
            name='id',
            field=models.UUIDField(default=uuid.UUID('0a80ae17-8779-4ed6-a812-293e86768f73'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='pokemoninstance',
            name='nickname',
            field=models.CharField(blank=True, default=None, max_length=80, null=True, verbose_name='custom name given by owner'),
        ),
    ]
