# Generated by Django 4.1.5 on 2023-01-25 06:44

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('pokemons', '0005_alter_person_first_name_alter_person_last_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemoninstance',
            name='id',
            field=models.UUIDField(default=uuid.UUID('e36ccae5-be77-4441-b024-132ca0cf0b97'), primary_key=True, serialize=False),
        ),
    ]
